"""empty message

Revision ID: 16386380775b
Revises: 
Create Date: 2024-07-16 15:16:06.587034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16386380775b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user_album')
    with op.batch_alter_table('user_album', schema=None) as batch_op:
        batch_op.drop_column('liked_at')

    with op.batch_alter_table('user_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.drop_column('liked_at')

    with op.batch_alter_table('user_track', schema=None) as batch_op:
        batch_op.drop_column('liked_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('user_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('order')

    with op.batch_alter_table('user_album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_at', sa.DATETIME(), nullable=True))

    op.create_table('_alembic_tmp_user_album',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('album_id', sa.VARCHAR(), nullable=True),
    sa.Column('favorited', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
