"""empty message

Revision ID: 35c55c4093c5
Revises: 32e7c8959965
Create Date: 2024-07-20 23:50:02.088820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c55c4093c5'
down_revision = '32e7c8959965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('album_id', sa.String(), nullable=True))
        batch_op.drop_column('album')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('album_id')
        batch_op.drop_column('album_name')

    # ### end Alembic commands ###
