"""empty message

Revision ID: 794c409d84e7
Revises: ce95a3cfe92f
Create Date: 2024-08-02 19:43:36.067691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794c409d84e7'
down_revision = 'ce95a3cfe92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artists_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('artists_id', sa.String(), nullable=True))
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('artists_id')
        batch_op.drop_column('artists_name')

    # ### end Alembic commands ###
